name: Label issues
'on':
  issues:
    types:
      - reopened
      - opened
jobs:
  label-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Dump github context
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Check xyz variable
        env:
          PAT_TOKEN: '${{ secrets.PAT_TOKEN1 }}'
        run: echo '${{ secrets.PAT_TOKEN1 }}'
        shell: bash
      - name: Install dependencies
        run: npm install
      - name: Label Issues
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          GITHUB_ISSUE_NUMBER: '${{github.event.issue.number }}'
          GITHUB_REPOSITORY_NAME: '${{github.event.repository.name }}'
          PAT_TOKEN: '${{ secrets.PAT_TOKEN1 }}'
        run: |
          npm install @octokit/rest
          npm install @actions/core
          node label-issues.js

